" =========================== General ===========================
" Automatically reloading .vimrc
autocmd! bufwritepost .vimrc source %

" show line number 
set number

" enable mouse
set mouse=a

" set font
set guifont=Monaco:h13

" syntax highlight
syntax on

" highlight current line/row
set cursorline
set cursorcolumn
hi cursorline cterm=bold ctermbg=237 ctermfg=none term=bold
hi cursorcolumn cterm=bold ctermbg=237 ctermfg=none term=bold

" highlight comment 
highlight Comment ctermfg=green guifg=green  

" =========================== Shortcut ===========================
" Ctrl + w for save
noremap <C-w> :w<CR>

" moving code blocks for better indentation
vnoremap < <gv
vnoremap > >gv

" file type config
autocmd FileType python setlocal ai tabstop=4 shiftwidth=4 expandtab
autocmd FileType yaml setlocal ai ts=2 sw=2 et

" =========================== Plugin ===========================
" Vundle (Vim Extensions Manager) config
" git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
set nocompatible              " required
filetype off                  " required
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
" Add all your plugins here (note older versions of Vundle used Bundle instead of Plugin)
Plugin 'Lokaltog/vim-powerline'
Plugin 'Yggdroot/indentLine'
" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" python editing needed
set nofoldenable

" powerline needed
set laststatus=2
let g:Powerline_symbols='unicode'


" :set foldexpr=getline(v:lnum)=~'^\\s*$'&&getline(v:lnum+1)=~'\\S'?'<1':1 
" autocmd BufWinLeave * if expand("%") != "" | mkview | endif
" autocmd BufWinEnter * if expand("%") != "" | loadview | endif
