" =========================== General ===========================
" Automatically reloading .vimrc 
autocmd! bufwritepost .vimrc source %

" show line number 
set number

" enable mouse
set mouse=a

" enable paste mode
set paste

" set font
set guifont=Monaco:h13

" syntax highlight
syntax on

" set tab as 4 spaces
set tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab
" paste text will break expandtab, 'set expandtab' will fix it

" highlight current line/row
set cursorline
set cursorcolumn
hi cursorline cterm=bold ctermbg=237 ctermfg=none term=bold
hi cursorcolumn cterm=bold ctermbg=237 ctermfg=none term=bold

" backspace setup fix auto indent problem
" http://vim.wikia.com/wiki/Backspace_and_delete_problems
set backspace=2

" highlight comment 
highlight Comment ctermfg=green guifg=green  

set conceallevel=0

" file type config
autocmd FileType python setlocal ai tabstop=4 shiftwidth=4 expandtab 
autocmd FileType python nnoremap <buffer> <F5> :exec '!python' shellescape(@%, 1)<cr>
autocmd FileType yaml setlocal ai ts=2 sw=2 et
autocmd FileType json setlocal ai ts=2 sw=2 et 
auto BufNewFile *.py 0r ~/workspace/vim/python.template

" foldexpr config
set foldenable
set foldmethod=expr
autocmd BufWinLeave * if expand("%") != "" | mkview | endif
autocmd BufWinEnter * if expand("%") != "" | loadview | endif
" #auto BufWinLeave * silent mkview
" #auto BufWinEnter * silent loadview

" auto folder cmd based space line 
" :set foldexpr=getline(v:lnum)=~'^\\s*$'&&getline(v:lnum+1)=~'\\S'?'<1':1 
" disable folder 
set nofoldenable

" =========================== Shortcut ===========================
" Ctrl + w for save
noremap <C-w> :w<CR>

" moving code blocks for better indentation
vnoremap < <gv
vnoremap > >gv

" vim installation to support YouCompleteMe
" sudo yum -y install gcc ncurses-devel automake gcc gcc-c++ kernel-devel cmake python-devel python3-devel
" git clone https://github.com/vim/vim.git
" cd vim
" ./configure --with-features=huge --enable-multibyte --enable-rubyinterp=yes --enable-pythoninterp=yes --enable-python3interp=yes --enable-gui=gtk2 --enable-cscope
" make
" sudo make install
" vim --version | grep python
" sudo update-alternatives --install /usr/bin/editor editor /usr/local/bin/vim 1
" sudo update-alternatives --set editor /usr/local/bin/vim
 
" =========================== Plugin ===========================
" Vundle (Vim Extensions Manager) config
" git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
set nocompatible              " required
filetype off                  " required
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
" Add all your plugins here (note older versions of Vundle used Bundle instead of Plugin)
" Plugin 'Lokaltog/vim-powerline'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'Yggdroot/indentLine'
" install YouCompleteMe
" $ cd ~/.vim/bundle
" $ git clone https://github.com/ycm-core/YouCompleteMe.git
" $ cd YouCompleteMe/
" switch back to python2
" $ git checkout legacy-py2
" $ git submodule update --init --recursive
" if hash error was shown for libclang-9.0.0-x86_64-unknown-linux-gnu.tar.bz2, it can be downloaded from https://gitee.com/ithewei/YCM/raw/e0aab9a7fe533855388b628849a9a53d94c1f35b/third_party/ycmd/clang_archives/libclang-9.0.0-x86_64-unknown-linux-gnu.tar.bz2
" $ ./install.py --clang-completer
" Plugin 'Valloric/YouCompleteMe'
Plugin 'farmergreg/vim-lastplace'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
Plugin 'dracula/vim', { 'name': 'dracula' }
Plugin 'tmhedberg/SimpylFold'
" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" python editing needed
autocmd FileType python setlocal nofoldenable

" powerline needed
set laststatus=2
let g:Powerline_symbols='unicode'

" Youcomplteme 
let g:ycm_path_to_python_interpreter='/usr/bin/python'
let g:ycm_seed_identifiers_with_syntax=1
let g:ycm_min_num_of_chars_for_completion=2
let g:ycm_autoclose_preview_window_after_completlion=1
autocmd InsertLeave * if pumvisible() == 0|pclose|endif

" lastplace
let g:lastplace_open_folds = 1

" indendline
let g:indentLine_char='┆'
let g:indentLine_enabled = 1 
let g:indentLine_setConceal = 0

" markdown show symbols
let g:vim_markdown_conceal = 0

" change color theme to oblivion
" colorscheme oblivion
" change color theme to dracula
colorscheme dracula
syntax on
highlight Comment ctermfg=green guifg=green


set t_Co=256
hi Normal ctermbg=none
highlight nonText ctermbg=NONE

" foldering
let g:SimpylFold_docstring_preview = 1
